/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import gradle.java.domain.OnlineShop;
import gradle.java.domain.ports.ProductRepository;
import gradle.java.domain.ports.UserInterface;
import gradle.java.infraestructure.dataaccess.Database;
import gradle.java.infraestructure.dataaccess.ProductWarehouse;
import gradle.java.infraestructure.presentation.CatalogFormatter;
import gradle.java.infraestructure.presentation.ProductFormatter;
import gradle.java.infraestructure.presentation.cli.CliUserInterface;

public class App {

  public static void main(String[] args) {

    ProductRepository database = new Database();
    gradle.java.domain.ports.CatalogFormatter catalogFormatter = new CatalogFormatter();
    gradle.java.domain.ports.ProductFormatter productFormatter = new ProductFormatter();
    ProductWarehouse productWarehouse = new ProductWarehouse();
    UserInterface userInterface = new CliUserInterface();

    OnlineShop onlineShop = new OnlineShop(database, catalogFormatter, productFormatter, productWarehouse, userInterface);

    onlineShop.run();

  }
}
