/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import gradle.java.domain.ProductRepository;
import gradle.java.infraestructure.Database;

public class App {
    public static void main(String[] args) {

        ProductRepository database = new Database();
        OnlineShop onlineShop = new OnlineShop(database);
        onlineShop.showProducts();
    }
}
