/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;


public class AppTest {
    @Test
    public void appTest() {
        assertEquals(1, 1);
    }
}
